import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp,readFile,writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createSetupServer } from '../server.mjs';
test('setup guards secrets, pairs, routes BYOK directly and revokes cloud token',async t=>{
 const values=new Map(),calls=[];
 const credentials={resolve:async k=>values.has(k)?{value:values.get(k)}:undefined,set:async(k,v)=>values.set(k,v),unset:async k=>values.delete(k)};
 const fetchImpl=async(url,opts={})=>{calls.push({url:String(url),opts});const path=new URL(url).pathname;
 if(path==='/desktop/auth/code/redeem')return Response.json({sessionToken:'jc_'+'1'.repeat(64),expiresIn:604800});
 if(path==='/health')return new Response('{}');
 if(path.endsWith('/start'))return Response.json({deviceSecret:'server-secret',userCode:'1234ABCD',expiresIn:300});
 if(path.endsWith('/poll'))return Response.json({status:'approved',sessionToken:'cloud-secret'});
 if(path==='/desktop/account')return Response.json({features:{model:true,retrieval:true}});
 if(path.endsWith('/logout'))return Response.json({loggedOut:true});
 return Response.json({choices:[{message:{content:'建议'}}]});
 };
 const stateDir=await mkdtemp(join(tmpdir(),'jinbao-setup-')),setup=await createSetupServer({credentials,stateDir,port:0,fetchImpl});
 t.after(setup.close);const base=setup.url.split('/#')[0],nonce=setup.url.split('#')[1];
 const request=(path,b,headers={})=>fetch(base+path,{method:b===undefined?'GET':'POST',headers:{'X-Jinbao-Setup':nonce,'Content-Type':'application/json',...headers},...(b===undefined?{}:{body:JSON.stringify(b)})});
 assert.equal((await fetch(base+'/api/status')).status,403);
 assert.equal((await request('/api/model',{mode:'cloud'},{Origin:'https://evil.test'})).status,403);
 assert.equal((await request('/v1/chat/completions',{messages:[]})).status,401);
 const start=await (await request('/api/login/start',{})).json();assert.equal(start.userCode,'1234ABCD');assert.ok(!JSON.stringify(start).includes('server-secret'));
 const poll=await(await request('/api/login/poll',{})).json();assert.deepEqual(poll,{status:'approved'});assert.equal(values.get('JINBAO_SERVICE_TOKEN'),'cloud-secret');
 assert.equal((await request('/api/model',{mode:'byok',baseUrl:'https://vendor.test/v1',model:'test-model',apiKey:'private-key'})).status,200);
 const persisted=await readFile(join(stateDir,'settings.json'),'utf8');assert.ok(!persisted.includes('private-key'));
 await writeFile(join(stateDir,'logs','lol-test.jsonl'),'{"game":"lol","kind":"state"}\n');
 const status=await (await request('/api/status')).json();assert.equal(status.validTail,true);assert.ok(!JSON.stringify(status).includes('private-key'));assert.ok(!JSON.stringify(status).includes('cloud-secret'));
 const local=values.get('JINBAO_LOCAL_ACCESS_KEY');
 assert.equal((await request('/v1/chat/completions',{messages:[{role:'user',content:'建议'}],model:'wrong'},{Authorization:'Bearer '+local})).status,200);
 const last=calls.at(-1);assert.equal(last.url,'https://vendor.test/v1/chat/completions');assert.equal(last.opts.headers.Authorization,'Bearer private-key');assert.equal(JSON.parse(last.opts.body).model,'test-model');
 assert.equal((await request('/api/model',{mode:'byok',baseUrl:'https://api.jinbaoai.top/v1',model:'x',apiKey:'x'})).status,400);
 assert.equal((await request('/api/model',{mode:'cloud'})).status,200);
 await request('/v1/chat/completions',{messages:[]},{Authorization:'Bearer '+local});assert.equal(calls.at(-1).opts.headers.Authorization,'Bearer cloud-secret');
 await writeFile(join(stateDir,'coach_live_state.json'),JSON.stringify({game:'lol',lastReply:{text:'先集合',at:123},privateContext:'do-not-return'}));
 const advice=await(await request('/api/advice')).json();assert.deepEqual(advice,{game:'lol',text:'先集合',updatedAt:123});
 await request('/api/logout',{});assert.equal(values.has('JINBAO_SERVICE_TOKEN'),false);
 assert.equal((await request('/api/login/code',{activationCode:'bad'})).status,400);
 const activated=await(await request('/api/login/code',{activationCode:' jb-'+'a'.repeat(32)+' '})).json();assert.deepEqual(activated,{status:'approved'});assert.equal(values.get('JINBAO_SERVICE_TOKEN'),'jc_'+'1'.repeat(64));assert.ok(!JSON.stringify(activated).includes('jc_'));assert.equal(JSON.parse(calls.at(-1).opts.body).activationCode,'JB-'+'A'.repeat(32));
 await request('/api/logout',{});assert.equal(values.has('JINBAO_SERVICE_TOKEN'),false);
});
